### ISSUE TITLE
code controls

### ISSUE THREAD

**Issue by gsaiganesh283** [gsaiganesh283/makeit-interview-portal#3]
![image](https://github.com/user-attachments/assets/1f6990a1-1e9b-49c5-9add-14314fbfa74e)

Arrange the code controls below the test cases with enlarge size like shown below

![image](https://github.com/user-attachments/assets/d5599f69-fcce-4be7-9f00-9b6e5e9a2e34)

**Comment by chakradhar3724** [comment]
It is changed and resolved

**Comment by gsaiganesh283** [comment]
make the code controls enlarge

code controls (run,reset,submit)

**Comment by chakradhar3724** [comment]
It is resolved now
