### ISSUE TITLE
Enlarge communication controls

### ISSUE THREAD

**Issue by gsaiganesh283** [gsaiganesh283/makeit-interview-portal#4]
![image](https://github.com/user-attachments/assets/30772b28-33c3-4b11-8c77-906a61f2737d)

enlarge the communication controls like shown below

![image](https://github.com/user-attachments/assets/ac3950d0-ee7a-4a9a-a45f-21bfa4fc48ff)

**Comment by chakradhar3724** [comment]
Enlarged the buttons

**Comment by gsaiganesh283** [comment]
not enlarged 

communication controls (Listen, send)

**Comment by chakradhar3724** [comment]
It is now enlarged
