### ISSUE TITLE
Make the Header as default

### ISSUE THREAD

**Issue by gsaiganesh283** [gsaiganesh283/makeit-interview-portal#5]
![image](https://github.com/user-attachments/assets/ae224187-97eb-424f-ad58-3e445f80e669)

![image](https://github.com/user-attachments/assets/d90218cd-de01-429d-b227-2f0b9cb32046)

Make the header as default 

**Explanation:** 

If the tab scroll's down then the header with MakeIT and back to dashboard should be stable.

**Comment by chakradhar3724** [comment]
This is issue is resolved
