### ISSUE TITLE
Database Update

### ISSUE THREAD

**Issue by gsaiganesh283** [gsaiganesh283/makeit-interview-portal#8]
1. Open XAMMP
2. check the status of mysql on
3. click on admin
4. click on interview_platform
5. Drop the test cases table
6. Open SQL
7. paste the below code
8. ```CREATE TABLE `testcases` (
  `id` int(11) NOT NULL,
  `input` varchar(50) NOT NULL,
  `output` varchar(50) NOT NULL
)```
9. Go
10. Again open SQL
11. paste the below code 
12. ```INSERT INTO `testcases` (`id`,`input`, `output`) VALUES
('1','2 4', '2'),
('2','3 9', '3');```
13. Go
14. now check the main page for testcases

**Comment by chakradhar3724** [comment]
Got the main page
